### ISSUE TITLE
Support for long genome name

### ISSUE THREAD

**Issue by Hocnonsense** [MrOlm/drep#127]
- Feature request

Recent years, `DASTool` is being popular. However, `DASTool` always put bins to `<custom_name>_DASTool_bins/`, so when I compare Bins from different folder, an `duplicate genome basenames` exception will be raised.

Is `dRep` possible to handle this problem? Or can I give a custom name to the genome in a tsv file? I think `ln` or `cp` the raw bins can expansion more easily. e.g. different version or waste storage

Thanks!

**Comment by MrOlm** [comment]
Hello,

At the moment the only way to fix the issue is to rename the genome names to be unique, either with a symlink or copying them (as you say). If I were you I would just rename them to include the name of the folder they are in using a tool like awk (if you are familiar with it).

Thank you for the feature request; I will look into doing this the next time I update dRep.

Best,
Matt

**Comment by Hocnonsense** [comment]
Thanks! Hoping `dRep` to be better :)
