### ISSUE TITLE
nearly identical genomes in separate secondary clusters

### ISSUE THREAD

**Issue by aistBMRG** [MrOlm/drep#136]
Hi Matt,

I know that the appearance of "unexpected" clustering has been discussed previously, I assume, and that this is addressed in the manual but I just wanted to clarify.

[1] Is it possible that genomes with 99.5% ANI can end up in different secondary clusters, as I am seeing? I guess it will depend on the dataset but have you encountered that?

[2] It seems that the above issues are often resolved by clustering the representatives again. I noticed that because I am combining different datasets that are first clustered separately and then the representatives combined and clustered.

Time permitting at your end, would you have any insights into this?

Fyi, I am running drep v3.2.2 as follows:
dRep dereplicate \
--processors 48 \
--completeness 50 \
--contamination 5 \
--genomeInfo mags_sr.info \
--genomes mags_sr.path \
--S_algorithm fastANI \
--P_ani 0.90 \
--S_ani 0.95 \
--cov_thresh 0.30 \
--coverage_method larger \
--clusterAlg average \
--completeness_weight 1 \
--contamination_weight 5 \
--N50_weight 0.5 \
--size_weight 0 \
--strain_heterogeneity_weight 0 \
--centrality_weight 1 

Thanks a lot!

Dieter

**Comment by MrOlm** [comment]
Hi Dieter,

1) I have seen this before, but only when doing `--multiround_primary_clustering` (which can rarely result in this due to the greedy nature of the algorithm). In your case, the only real way for this to happen would be if nearly identical genomes ended up in different primary clusters (based on mash). This could happen if they're both really incomplete (as Mash treats incompleteness by lowering ANI). I would run a separate dRep run with just those two genomes and see what the mash ANI and secondary ANI is to get a hint at what's going on.

2) Yes I've also seen this, which is why I recently added the option `--run_tertiary_clustering`. All that does is compare the winners again at the end. I implemented this specifically to handle discrepancies introduced by greedy algorithms (which you're not using in this case), but you could always add it to your command as well.

Hope this answers you question.

Best,
Matt

**Comment by aistBMRG** [comment]
Hi Matt,

Thanks for the quick and helpful response. 

Looking into the issue a bit more yesterday indicated it may be related to the incompleteness of the genomes, as you touched upon. I will explore more by running some smaller tests with subsets of genomes as you suggested.

Best,

Dieter
