### ISSUE TITLE
dRep for proteome

### ISSUE THREAD

**Issue by jianshu93** [MrOlm/drep#138]
Hi Matt,

Since mash v 2.3, there are options to do estimation of genomic distance based on amino acid (proteome of a genome), I am thinking whether a dereplicate_aa workflow could also be interesting to you. I see a number of applications but we do no have a proteome based dereplication tool. could use mash to do preclustering and  then the compareM aai_wf to calculate AAI within each cluster. I see some very good correlation between Mash distance and blastp based AAI. Any interest?

Thanks,

Jianshu

**Comment by MrOlm** [comment]
Hi Jianshu,

Yes, I do like the idea of calculating genome distances based on amino acid space, but I just haven't implemented it yet because I've been busy with other projects. I've had good luck with MMseqs2 for straight proteome dereplication. I'd be happy to look at / accept a pull-request if you're interested in implementing this feature, but otherwise I am too busy with other things to work on it.

Thanks for the suggestion,
Matt
