### ISSUE TITLE
Passing checkM input, but dRep is still running checkM?

### ISSUE THREAD

**Issue by sterrettJD** [MrOlm/drep#188]
Hi Matt,

I hope you're doing well! I've been trying to dereplicate some genomes that I've already run checkM on. Since checkM took a while to run, I'm hoping to avoid rerunning it, so I'm passing the formatted checkM output to dRep under the `--genomeInfo` flag.

However, dRep is still running checkM. Here is the output:

> ***************************************************
>     ..:: dRep dereplicate Step 1. Filter ::..
> ***************************************************
>     
> Will filter the genome list
> 2,951 genomes were input to dRep
> Calculating genome info of genomes
> 100.00% of genomes passed length filtering
> Running prodigal
> Running checkM
> Running checkM in 2 chunks
> Running checkM chunk 0
...

Is there any way to prevent dRep from running checkM after I've passed my `genomeInfo`? I'm currently testing if passing both `--genomeInfo`  and `--ignoreGenomeQuality` solves this, but could you answer these questions? 

1. If I pass a genome info file and the `ignoreGenomeQuality` flag, will it use the genome info file I provided? Or does it always stick to N50 and length when `ignoreGenomeQuality` is passed?
2. If it will not use the genome info file I provided, is there a flag I could pass to get it to use my genome quality file and not rerun checkM?
3. If there's no way to prevent it from running checkM, does checkM run with the same number of threads I passed to dRep?
4. If the threads don't get passed to checkM, could I speed it up with `--checkm_group_size`?

For reference, my genomeInfo file is formatted as such:
> genome,Marker lineage,# genomes,# markers,# marker sets,0,1,2,3,4,5+,completeness,contamination,Strain heterogeneity
> LG052.bin.61,p__Proteobacteria (UID3887),1487.0,256.0,161.0,0.0,256.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
> LG050.bin.27,k__Bacteria (UID2329),174.0,149.0,89.0,0.0,148.0,1.0,0.0,0.0,0.0,100.0,1.12,0.0

And I'm running dRep with the following command:

> dRep dereplicate --genomes ../hiv.t32.n40.metaspades.metabat2/bins_to_derep/*.fa \
>         -p 16 \
>         --debug \
>         --genomeInfo ../hiv.t32.n40.metaspades.metabat2.checkm/checkM.stats.csv \
>         ./ # specifies current directory as work directory

Thanks!
John

**Comment by MrOlm** [comment]
Hi John,

Nice hearing from you.

Passing external genome information has to be in a specific format, not the standard format generated by checkM. See here for more info - https://drep.readthedocs.io/en/latest/advanced_use.html#using-external-genome-quality-information. If you want to pass the genome info to dRep this way, you'll need to reformat your input to conform.

Another hacky option is to copy the `Chdb.csv` folder from one dRep run into the `data_tables` folder of your new dRep run. This will require you to first create a work directory shell to run dRep out of. I don't recommend this method just because it's pretty hacky.

To answer your questions:

1) `ignoreGenomeQuality` will make it ignore the genome info you input, so that's not what you want.

2) Formatting the info as above will make dRep use that info and not re-run checkM

3) I believe it does use the same number of threads

4) No, this option is just to make it so checkM doesn't crash by having too many input genomes.

Let me know if this doesn't work for you

Mat

**Comment by sterrettJD** [comment]
Hey Matt,

Thanks for the quick reply! This was helpful.

After poking around some more, I realized that though I had reformatted the checkM output and renamed the column headers, I had left the `genome` column as the Bin Id from checkM, rather than the filepath. I fixed that, and now it's working without rerunning checkM. 

Thanks for your help,
John

**Comment by MengxueZHANG0120** [comment]
The extension of my bins is **.fa**. I used the filename of the genome **with its extension** under "genome" column, like showing in the website (https://drep.readthedocs.io/en/latest/advanced_use.html#using-external-genome-quality-information).
Otherwise dRep cannot catch the .csv file and will still run CheckM. 

I don't know if this happens because of my different extension, as the help file of dRep (v2.6.3) says:
"--genomeInfo GENOMEINFO  location of .csv file containing quality information on the genomes. Must contain: ["genome"(**basename** of .fasta file of that genome)".

**Comment by MrOlm** [comment]
Hi @MengxueZHANG0120 - that's quite annoying, sorry you're experiencing this. If you run dRep on just ilke 3 or 4 genomes (so it goes quick) and open the resulting file `Bdb.csv`, the column `genome` is what that genomeInfo is looking for.

Best,
Matt
