### ISSUE TITLE
Inquiry Regarding dRep Dereplication Process and Result Validity

### ISSUE THREAD

**Issue by rzhan186** [MrOlm/drep#216]
Hello Dr. Olm, 

I hope this message finds you well. Recently, I executed the dereplication function with the following command:

```
dRep dereplicate -p 32 $output -g $input/*.fasta \
--genomeInfo $report \
--completeness 50 \
--contamination 25 \
--S_ani 0.98 \
--multiround_primary_clustering \
--run_tertiary_clustering
```
During the process, the log file indicated several critical errors during step 2, and an AssertionError in Step 4. Despite these error messages, I observed that dRep completed the task and produced the dereplicated bins.

I am a bit concerned about the reliability of these results due to the encountered errors. Would you advise considering these bins as trustworthy, or do you recommend addressing the errors thoroughly until the process is error-free?

For your reference, I have attached the log file detailing the errors encountered during the dereplication process.

[drep-raw-bins-individual-assembly.log](https://github.com/MrOlm/drep/files/13561945/drep-raw-bins-individual-assembly.log)

Thanks for your help!

Rui

**Comment by MrOlm** [comment]
Hi Rui,

Yes OK- this is a problem with fastANI. For some reason it's failing when running 1 cluster of genomes (primary cluster 271); that's what the first errors refer to. FastANI does randomly crash sometimes, which is why dRep automatically tries to re-run. But crashing twice in a row like this indicates that there's something wrong with at least one of the genome files themselves that's causing the error.

The second error with the "centrality" is failing because not all genomes were compared in the first step, because of this fastANI error.

Tracking this down can be confusing. You'll first want to run dRep with `-d`, which will create logs for each fastANI run. You then can search these logs for the particular run that's failing (in this case it would be run xushelypnv) to see the error.

Alternatively, you could manually try and figure out what the problem is with at least 1 genome in primary cluster 271 of this current run.

Common things that could be wrong include foreign characters in the .fasta file, a corrupt .fasta file, or a fasta file that ends in .gz but that is not compressed (or vice versa).

Hope this helps,
Matt

**Comment by rzhan186** [comment]
Hi Dr. Olm,

Thanks for the detailed answers, I will try to troubleshoot following your recommendations! 

Best,
Rui
