### ISSUE TITLE
python 3 for drep but python 2 for checkm

### ISSUE THREAD

**Issue by nick-youngblut** [MrOlm/drep#33]
Based on looking at the `drep` python code and [Issue 22](https://github.com/MrOlm/drep/issues/22), it appears that drep requires python3. I don't see such a requirement specified in the `setup.py` file, but still, it appears to be python3 dependent. However, `drep` has `checkm` as a dependency, which is only compatible with python2. This has caused some issues with the bioconda drep recipe. It would be very helpful to make `drep` python2 compatible so that it can "play nicely" with checkm.

**Comment by nick-youngblut** [comment]
To be more specific, installing `drep` from bioconda creates the following error:

```
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************

Will filter the genome list
Calculating genome info of genomes
100.00% of genomes passed length filtering
Running prodigal
Running checkM
Program checkm is not working!! Im going to crash now
```

I'm guessing this is due to the initial database setup for `checkm`. If I try and run checkm to initialize the setup, then I get the following:

```
$ checkm
  File "/ebio/abt3_projects/databases/miniconda3/envs/metaphlan2_db/bin/checkm", line 58
    print ''
           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('')?
```

With python2:

```
$ python2 $(which checkm)
Traceback (most recent call last):
  File "/ebio/abt3_projects/databases/miniconda3/envs/metaphlan2_db/bin/checkm", line 36, in <module>
    from checkm import main
ImportError: No module named checkm
```

So `checkm` is currently not working with `drep` for the bioconda install.

**Comment by MrOlm** [comment]
Hi Nick,

This is a good idea and could help a lot with checkM troubles. I'm working on it now- I'll let you know when finished

-Matt

**Comment by jolespin** [comment]
Any progress on this?

**Comment by MrOlm** [comment]
There is progress but it's slow going. Doing this is harder than I initially thought, as dRep currently uses some functionality of python3 that's not available in python2 to speed things up. In making dRep compatible with python2 I don't want to give it a performance hit, so it's requiring some thinking to change things around.

**Comment by MrOlm** [comment]
Great- glad it's working and thanks for the update. Not sure if `checkm` plans to upgrade to python3, but the author seems to really like python2 so I'm not holding my breath

**Comment by Mattstorey** [comment]
Bioconda implementation would be great! In the meantime, what's the best way to set up the two needed python envs to get checkM to play with dRep? I'm hitting road blocks with everything I have tried. I have all dependencies working independently, but not together get the same "Im going to crash now" error.

**Comment by MrOlm** [comment]
Hey Matt,

The way that I handle it is by using pyenv. This allows you to have python2 and python3 available to call at the same time. Brief instructions are here: https://drep.readthedocs.io/en/latest/installation.html#pyenv

Alternatively, as you said you have them working separately, you can just run checkM on it's own and then provide the results to dRep. That way you never have to be able to call both python2 and python3 at the same time. Instructions for that are here: https://drep.readthedocs.io/en/latest/advanced_use.html#using-external-genome-quality-information

Finally, you said you keep hitting the "I'm going to crash now" error. You can see what dependencies dRep can access before you run it with the command `$ dRep bonus testDir --check_dependencies`. That way you can tell if the run is going to work or not without having to wait for it to crash.

Best,
-Matt

**Comment by mb1069** [comment]
Hey @MrOlm, I just encountered the same issue when using the docker container for this. Any suggestions on how to get around this issue, or is there a fix you have in mind which I could implement?

**Comment by MrOlm** [comment]
Hey @mb1069 - thanks for the implementation offer. There are a couple of different workarounds (pyenv to call both python2 and python3 programs; running checkM separately and then providing the results to dRep), but as I'm not familiar with docker or bioconda, I'm not sure how applicable either of those solutions are. Another workaround that _should_ work would be adjusting the shebang line in either dRep or checkM to explicitly call `python2` or `python3`, but I haven't personally verified that it works.

The couple of possible permanent solutions would be 1) replace the use of checkM with another program that doesn't use python2, 2) upgrade checkM to work with python3, or 3) re-write dRep to be both python2 and python3 compatible.

I've worked on (3) a bit, but there are some somewhat complex areas on which dRep relies on functionality that's only in python3. Additionally it uses a couple of dependencies (pandas, seaborn, matplotlib) that work with python2 at the moment, but which are dropping support soon (https://python3statement.org/). Because python2 is in the process of being sunsetted, I'm hesitant to re-write dRep to be compatible with it. 

Sorry for the long answer. Let me know if you come up with a solution and I'd be happy to check it out and push it to the `master` branch.

Best,
Matt

**Comment by alienzj** [comment]
I choose upgrade checkM to work with python3. Come on~

**Comment by jolespin** [comment]
I agree, that would make life a lot easier for me too . We’re on the wrong GitHub for that tho :(

**Comment by astrophys** [comment]
I got this to work by modifying checkm.  You still run drep in a python3 environment (setting `PYTHONPATH` to your python libs and all), but the trick is to modify the checkm executable.

Towards the top I have added : 


```
sys.path= ['/home/user/local/checkm/lib/python2.7/site-packages',
           '/opt/anaconda-2.3.0/lib/python2.7/site-packages/',
           '/opt/anaconda-2.3.0/lib/python2.7/',
           '/gpfs0/export/opt/anaconda-2.3.0/lib/python2.7/lib-dynload/']
```
This means when drep gets the the checkm part, checkm looks in the new sys.path instead of inheriting the sys.path set by using `PYTHONPATH`

**Comment by MrOlm** [comment]
Awesome! Thanks for posting, Mike. If you don’t mind, could you explain just a bit about how you identified those 4 python2 directories that you added? Like, how would someone do that on their own computer?

Similarly, I assume you identified the checkm executable using the command “which checkm”?

Thanks again,
-Matt

**Comment by astrophys** [comment]
In order:
1. `/home/user/local/checkm/` is where I installed `checkm-genome` through `pip` (e.g. `pip install --prefix /home/user/local/checkm --ignore-installed`).  `pip` installs the python libs under `lib/python2.7/site-packages/`.  `sys.path` must point there in order to find the `checkm` module so you can import it (i.e `import checkm`). 

2. `/opt/anaconda-2.3.0/lib/python2.7/site-packages/` is where Anaconda installed all the python dependencies (e.g. `numpy`, `scipy`, etc.)

3-4.  I fired up the `python2` that I use to run checkm.  I ran 
```
import sys
sys.path
```
These other paths (3 and 4) where in what that printed out, so I figured they were important.

**Note - 1**: I don't exactly recall how I got `checkm`, but I'm fairly sure I used `pip`.  Order matters here.  You want the `/home/user/local/checkm/lib/python2.7/site-packages` to be first because `checkm` may come with a different, incompatible versions of things like `numpy`.  If the system `numpy` is found first because 2 is ordered before 1, then `checkm` might break.

**Note - 2**:  I used `--ignore-installed` when installing `checkm` to prevent `pip` from clobbering the system libraries (e.g. `numpy`).  The consequence of clobbering the system `numpy` is that you may break the functionality of other programs depending on that version of `numpy`. If you order your `sys.path` as above you should be fine when running `checkm`.

**Comment by apcamargo** [comment]
CheckM is now Python 3: https://github.com/Ecogenomics/CheckM/releases/tag/v1.1.0

**Comment by Mattstorey** [comment]
Cool!

**Comment by alienzj** [comment]
Cool!

**Comment by MrOlm** [comment]
Documentation has been updated to reflect checkM in python3. Thanks for all your help and patience!
