### ISSUE TITLE
how to set dependencies

### ISSUE THREAD

**Issue by TomhitsJerry** [MrOlm/drep#39]
i am new at bioinformatics，and not sure how to set all the dependencies correctly.
Download all the dependiencies，and should i set the path to let dREP know？or where should i download  the dependencies？

**Comment by MrOlm** [comment]
Hello,

You want the dependencies set up so that when you type them into your console, they work. For example, when you type into your console: `$ mash -h`, it should bring up the mash help page.

You usually do this by downloading dependencies, installing them, and adding them to your PATH.

Also, check out the following page to see what dependencies you'll actually need:

https://drep.readthedocs.io/en/latest/installation.html#dependencies

You don't want to mess with installing more dependencies than you have to :)

Hope that helps!
-Matt
