### ISSUE TITLE
FileNotFoundError when performing secondary clustering

### ISSUE THREAD

**Issue by alexmsalmeida** [MrOlm/drep#46]
Hi,

I am running dRep v.2.2.4 on ~5000 genomes and am having issues during the secondary clustering step. The log snippet can be found below:

```***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
Calculating genome info of genomes
100.00% of genomes passed length filtering
5372.26% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Clustering Step 1. Parse Arguments
Clustering Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
2b. Cluster pair-wise MASH clustering
3287 primary clusters made
Step 3. Perform secondary clustering
Running 353383 ANImf comparisons- should take ~ 5521.6 min
Traceback (most recent call last):
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/bin/dRep", line 33, in <module>
    controller.parseArguments(args)
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/lib/python3.7/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/lib/python3.7/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/lib/python3.7/site-packages/drep/d_workflows.py", line 36, in dereplicate_wrapper
    drep.d_cluster.d_cluster_wrapper(wd, **kwargs)
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/lib/python3.7/site-packages/drep/d_cluster.py", line 78, in d_cluster_wrapper
    data_folder, wd=workDirectory, **kwargs)
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/lib/python3.7/site-packages/drep/d_cluster.py", line 200, in cluster_genomes
    ndb = compare_genomes(bdb, algorithm, data_folder, **kwargs)
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/lib/python3.7/site-packages/drep/d_cluster.py", line 817, in compare_genomes
    df = run_pairwise_ANImf(genome_list, working_data_folder, **kwargs)
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/lib/python3.7/site-packages/drep/d_cluster.py", line 964, in run_pairwise_ANImf
    df = process_deltafiles(deltafiles, org_lengths, **kwargs)
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/lib/python3.7/site-packages/drep/d_cluster.py", line 707, in process_deltafiles
    tot_length, tot_sim_error = parse_delta(deltafile)
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/lib/python3.7/site-packages/drep/d_cluster.py", line 645, in parse_delta
    for line in [l.strip().split() for l in open(filename, 'r').readlines()]:
FileNotFoundError: [Errno 2] No such file or directory: '/hps/nobackup2/production/metagenomics/clustering/iter_8/drep32/data/ANImf_files/ERS608499_12.fa/ERS608499_12.fa
_vs_SRS475589_82.fa.delta.filtered'
```

This is not the first time I've encountered this error. It seems to occur when I launch de-replication of large numbers of genomes (5K-6K seems to be the limit). I am usually able to solve it if I split the genomes in different batches and de-replicate them separately first. However, for this particular set I'd like to do all of them in one-go. It doesn't seem to be a RAM memory issue, as I've tried allocating much more memory (>100GB) than what the program is using. Could it be just a filesystem issue when there are too many ANImf comparisons being made? 

Many thanks in advance.

Best,
Alex

**Comment by alexmsalmeida** [comment]
Following this, it seems to be a problem when running nucmer:

```
nucmer --mum -p /hps/nobackup2/.../ERS608499_12.fa/ERS608499_12.fa_vs_SRS475589_82.fa 
 -c 65 -g 90 /hps/nobackup2/.../ERS608499_12.fa /hps/nobackup2/.../SRS475589_82.fa

delta-filter -r -q /hps/nobackup2/.../ERS608499_12.fa/ERS608499_12.fa_vs_SRS475589_82.f.delta 
 > /hps/nobackup2/.../ERS608499_12.fa/ERS608499_12.fa_vs_SRS475589_82.fa.delta.filtered
```

Seems to be looking for a file called ERS608499_12.fa_vs_SRS475589_82.f.delta instead of ERS608499_12.fa_vs_SRS475589_82.fa.delta. Any idea on why this might be?

**Comment by MrOlm** [comment]
Wow this is bizarre- never encountered anything like this before. It does seem like it could be a filesystem problem, but I've run with 10,000 genomes and it's been fine, so if so it would be somewhat specific to your machine. A couple of thoughts:

1) you could try a different algorithm (for example `--S_algorithm ANIn`) is similar to the one you're using but doesn't have a filtering step (which seems to be where this is messing up). As a result it also only makes 1 file instead of 2. ANImf is generally better, but honestly they both give extremely similar results in most cases so I wouldn't be worried about it.

You could also try raising the `-pa` threshold to `0.95` or something, so that you end up doing less genomic comparisons and thus making less files?

2) you could try and run with `--debug`, which would tell you exactly the error that nucmer is crashing with, but would make way more files. The fact that this works on subsets of the the genome list makes me hesitant to think that this is a problem with some genome, though (which is what `--debug` would tell you)

3) Figuring out if it's the same genome that its crashing on every time, or if it crashes after some number of comparisons would be helpful to pointpointing the problem. If it's a filesystem error, it could be too many files in one directory (each genome has its own folder storing these .delta file, so this could happen if you end up with a giant primary cluster). Maybe try and make another couple files in the directory `'/hps/nobackup2/production/metagenomics/clustering/iter_8/drep32/data/ANImf_files/ERS608499_12.fa/` and see if you get some sort of error?

4) I got an email that it seemed to be a problem with a file ending with `.f.delta` instead of `.fa.delta`, but that isn't showing up here. Was that comment deleted or is it still a clue we should consider?

Best,
-Matt

**Comment by alexmsalmeida** [comment]
Hi Matt,

Thanks for the detailed response. It most likely is a random filesystem issue as just isolating those two genomes that were giving me issues does not result in the same error (I can de-replicate them without a problem).

I will try your additional suggestion of using the ANIn algorithm to see if it goes through. I am also re-running it again with --debug to see if I can spot anything else. 

It doesn't seem to be related to too many files in one directory (that particular one has ~1000 files, which is under the recommended limit in our filesystem of 5000 files). I am also able create additional files in that same dir without a problem.

I deleted that last comment because I realized it was a copy and paste error, so sorry about that.

Will try to figure it out, thanks for your help.

Alex
