### ISSUE TITLE
figures

### ISSUE THREAD

**Issue by CristianUNR** [MrOlm/drep#51]
Hi, 
Are there any way to get the figures in another format than pdf? like .emf or .svg?

Thanks!

Cristian.-

**Comment by MrOlm** [comment]
Hi Cristian,

Sorry for the long response time! Unfortunately because many of the figures have multiple pages it is not possible to save them in a different format without significant changes to the code base. You could always convert them to other formats using 3rd party software. When you open the .pdf files in Adobe Illustrator, for example, all of the lines and texts objects are vectorized and able to be manipulated.

Best,
Matt

**Comment by CristianUNR** [comment]
Hi Matt,
don´t worry. I solved this problem open pdf file with Inkscape, this
program vectorized the file, so then I could edited.


Thanks!

*Dr. Cristian Suárez*
Facultad de Ciencias Médicas
Universidad Nacional de Rosario
Suipacha 570 - CUAS IV 1º Piso
Rosario (2000) Argentina
