### ISSUE TITLE
ANImf comparisons running time 

### ISSUE THREAD

**Issue by genetalks-fred** [MrOlm/drep#53]
Hi
I have 24 thousand bins for drep, after completion(50) and contamination(10) filtering, the log file give the estimated time consuming 28184 min, about 19 days? Anything i can do to accelerate this process? 
The parameter i run drep is "-p 32 -comp 50 -con 10".

thanks!

**Comment by MrOlm** [comment]
Hi genetalks-fred,

Unfortunately there's not a lot you can do- that's a ton of genomes! Your only real option to speed it up would be to use `--skip_secondary`, and just run genome clustering with Mash. This would speed things up a ton but is not recommended because Mash is not very accurate with incomplete genomes, however.

You could also try gANI instead of ANImf; it is a bit faster than ANImf (it will take approximately half as long as ANImf).

Good luck!
Matt
