### ISSUE TITLE
 checkM failed !!!

### ISSUE THREAD

**Issue by shradhakhater** [MrOlm/drep#57]
Hi,
I am trying to run filter module of drep with genomes supplied as Bdb.csv file:
dRep filter ~/drep_pub -p 12

I keep getting error at the checkM step.  Here is the log output that I am getting:
07-25 12:04 DEBUG    Filtering genomes by size
07-25 12:04 INFO     100.00% of genomes passed length filtering
07-25 12:04 DEBUG    Running CheckM
07-25 12:04 INFO     Running prodigal
07-25 12:04 INFO     Past prodigal runs found- will not re-run
07-25 12:04 INFO     Running checkM
07-25 12:04 DEBUG    Running CheckM with command: ['/home/balaji/.pyenv/shims/checkm', 'lineage_wf', '/home/balaji/drep_pub/data/prodigal/', '/home/balaji/drep_pub/data/checkM/checkM_outdir/', '-f', '/home/balaji/drep_pub/data/checkM/checkM_outdir//results.tsv', '--tab_table', '-t', '12', '--pplacer_threads', '12', '-g', '-x', 'faa']
07-25 12:04 DEBUG    Running CheckM with command: ['/home/balaji/.pyenv/shims/checkm', 'qa', '/home/balaji/drep_pub/data/checkM/checkM_outdir/lineage.ms', '/home/balaji/drep_pub/data/checkM/checkM_outdir/', '-f', '/home/balaji/drep_pub/data/checkM/checkM_outdir/Chdb.tsv', '-t', '12', '--tab_table', '-o', '2']
07-25 12:04 ERROR    !!! checkM failed !!!
If using pyenv, make sure both python2 and python3 are available (for example: pyenv global 3.5.1 2.7.9)

I am using pyenv.
$ pyenv global
3.5.1
2.7.9

Also, drep check_dependencies work fine:
dRep bonus testDir --check_dependencies
Loading work directory
Checking dependencies
mash.................................... all good        (location = /home/balaji/softwares/mash-Linux64-v2.1.1/mash)
nucmer.................................. all good        (location = /home/balaji/softwares/mummer-3.9.4alpha/bin/nucmer)
checkm.................................. all good        (location = /home/balaji/.pyenv/shims/checkm)
ANIcalculator........................... all good        (location = /home/balaji/softwares/ANIcalculator_v1/ANIcalculator)
prodigal................................ all good        (location = /home/balaji/softwares/prodigal/prodigal)
centrifuge.............................. !!! ERROR !!!   (location = None)
nsimscan................................ all good        (location = /home/balaji/softwares/ANIcalculator_v1/nsimscan)

Please help.
Thanks

**Comment by MrOlm** [comment]
Hello,

Hmm, interesting. I’m not quite sure what the problem is at the moment. If
try again with the “--debug” option, drep will make a folder called
“cmd_logs” in the log directory, in which it will tell you the exact error
that checkm is throwing. If you let me know what that says it should help
solve the problem.

Thank you,
Matt

On Jul 25, 2019, at 3:29 PM, shradhakhater <notifications@github.com> wrote:

Hi,
I am trying to run filter module of drep with genomes supplied as Bdb.csv
file:
dRep filter ~/drep_pub -p 12

I keep getting error at the checkM step. Here is the log output that I am
getting:
07-25 12:04 DEBUG Filtering genomes by size
07-25 12:04 INFO 100.00% of genomes passed length filtering
07-25 12:04 DEBUG Running CheckM
07-25 12:04 INFO Running prodigal
07-25 12:04 INFO Past prodigal runs found- will not re-run
07-25 12:04 INFO Running checkM
07-25 12:04 DEBUG Running CheckM with command:
['/home/balaji/.pyenv/shims/checkm', 'lineage_wf',
'/home/balaji/drep_pub/data/prodigal/',
'/home/balaji/drep_pub/data/checkM/checkM_outdir/', '-f',
'/home/balaji/drep_pub/data/checkM/checkM_outdir//results.tsv',
'--tab_table', '-t', '12', '--pplacer_threads', '12', '-g', '-x', 'faa']
07-25 12:04 DEBUG Running CheckM with command:
['/home/balaji/.pyenv/shims/checkm', 'qa',
'/home/balaji/drep_pub/data/checkM/checkM_outdir/lineage.ms',
'/home/balaji/drep_pub/data/checkM/checkM_outdir/', '-f',
'/home/balaji/drep_pub/data/checkM/checkM_outdir/Chdb.tsv', '-t', '12',
'--tab_table', '-o', '2']
07-25 12:04 ERROR !!! checkM failed !!!
If using pyenv, make sure both python2 and python3 are available (for
example: pyenv global 3.5.1 2.7.9)

I am using pyenv.
$ pyenv global
3.5.1
2.7.9

Also, drep check_dependencies work fine:
dRep bonus testDir --check_dependencies
Loading work directory
Checking dependencies
mash.................................... all good (location =
/home/balaji/softwares/mash-Linux64-v2.1.1/mash)
nucmer.................................. all good (location =
/home/balaji/softwares/mummer-3.9.4alpha/bin/nucmer)
checkm.................................. all good (location =
/home/balaji/.pyenv/shims/checkm)
ANIcalculator........................... all good (location =
/home/balaji/softwares/ANIcalculator_v1/ANIcalculator)
prodigal................................ all good (location =
/home/balaji/softwares/prodigal/prodigal)
centrifuge.............................. !!! ERROR !!! (location = None)
nsimscan................................ all good (location =
/home/balaji/softwares/ANIcalculator_v1/nsimscan)

Please help.
Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MrOlm/drep/issues/57?email_source=notifications&email_token=ADGNMTO644V3Q4DVB5JQC2TQBFI4LA5CNFSM4IGXW46KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HBM6Y4Q>,
or mute the thread
