### ISSUE TITLE
similarity rate in filter

### ISSUE THREAD

**Issue by ucassee** [MrOlm/drep#58]
I use dREP to select representative bins for seven metagenomes .I want to know whether there is a parameter to set the similarity rate to filter bins.
I use `dRep dereplicate -p 28 -comp 50 -con 10 -l 10000 output_dir/ -g /path/to/genomes/*.fasta` this command to dereplicate 540 bins and there are 450 bins left. I want to know the similarity rate between the selected bin and filtered bin?

Thanks in advance.

**Comment by ucassee** [comment]
In https://drep.readthedocs.io/en/master/choosing_parameters.html this page. You mentioned two parameter  `Minimum secondary ANI` and `Minimum aligned fraction`. I want to know how to set these and use this to dereplicate bins.

**Comment by MrOlm** [comment]
Hello,

I see that you found that relevant page in the manual, which discusses how you should think about choosing these values. The most important value that you can pick is the `Minimum secondary ANI`- some additional information on this value can be seen at this blog post- https://microbe.net/2017/02/15/are-these-microbes-the-same/. 

The default value is 99% ANI, which means that in your case, in all cases where multiple genomes were at least 99% similar to each other, one genome was chosen to be in the final genome set. 

Do you have any questions or is anything confusing about the advice stated in the manual?

Best,
Matt

**Comment by ucassee** [comment]
What is the default set of `Minimum aligned fraction`. If 40% of the genome of binA  is the same as binB and 60% of the binA is different. In this case, will one of them be filtered?  How to set this threshold?
Thanks in advance!

**Comment by MrOlm** [comment]
Hello,

The default minimum aligned fraction is 10%- so yes, in your example case one of those genomes would be filtered. You can change this if you'd like based on the `-nc` parameter. In practice, however, genome alignment fractions seem to be very high or very low. You can look at `data_tables/Ndb.csv` to see what the alignment coverage values actually are. The low alignments tend to be due to a shared transposon or something of that nature.

Best,
Matt
