### ISSUE TITLE
Understanding warnings

### ISSUE THREAD

**Issue by adityabandla** [MrOlm/drep#61]
I ran dRep with default settings for MASH & ANI of 99.9% for the secondary clustering with gANI. I get a set of warnings at the end of the workflow and I understand these are meant to 1. warn if highly similar genomes are being split into different primary clusters and 2. when genomes are the limit of ANI during the secondary comparison step

However, I am not able to completely understand what the following means
`CLUSTERING WARNING: Primary cluster 195 has a high self-comparison value`
Doe this warning pertain to the MASH step or the gANI step? I am assuming its the gANI step and it's just telling that I have a bunch of highly similar genomes in this primary cluster?

**Comment by MrOlm** [comment]
Hello,

Sorry for the lack of documentation. This warning is actually stating that in that primary cluster, an ANI value for comparing a genome to itself is within the warning distance of your threshold.

By default the warning distance is 0.25, and because your threshold is 0.1, this warning will be tripped erroneously all the time.

gANI especially tends to always have very high self-vs-self ANI comparisons, so if I were you, I would ignore this type of warning.

Best,
Matt
