### ISSUE TITLE
Clustering at 0.95 identity threshold

### ISSUE THREAD

**Issue by elizabethmcd** [MrOlm/drep#74]
Hi Matt,

I'm having some issues dereplicating a set of genomes. I want to have representative species clusters, where it picks the "best" genome for a cluster of genomes that are at least 95% similar to each other. My understanding is that the default clustering is at 0.99. I've changed the -pa and -sa flags to 0.95, and still get the same number of bins at the end. I read issue #44, and may still be confused about what's going on. I manually ran my own ANI comparisons, and after using those flags I still have a bunch of genome groups that are 99% similar to each other. Like I said, I might be using the wrong flags or not understanding what's going on under the hood, but thought I would ask what the best way would be to get to representative species clusters. 

Thanks.

**Comment by MrOlm** [comment]
Hello,

So the problem is probably happening because you're changing the -pa flag. You want to keep that low (the default of 0.9 usually works, but you could even do 0.8 if your genomes are somewhat partial. -sa is the ANI value that you want to adjust, so in this case, set it to 0.95.

With those parameters set this should do the de-replication that you're looking for. If you're still having troubles, please let me know and send over a copy of the command that you're running.

Best,
Matt
