### ISSUE TITLE
ERROR    !!! checkM failed !!!

### ISSUE THREAD

**Issue by sleepvet** [MrOlm/drep#77]
I get a chekM failed error hit when I run "dRep dereplicate /mnt/10t/mzy/72sample/bin/derep/ -g /mnt/10t/mzy/72sample/bin/*.fa -p 10 -comp 80 -con 10 -str 100 -strW 0 --debug".  There are 2 major error comments in log files: 
_RecursionError: maximum recursion depth exceeded while calling a Python object_

_FileNotFoundError: [Errno 2] No such file or directory: '/mnt/10t/mzy/72sample/bin/derep/data/checkM/checkM_outdir/storage/checkm_hmm_info.pkl.gz'_

I attach all log files, could you please check it for me and tell me how to deal with it?

[logger.log](https://github.com/MrOlm/drep/files/4532808/logger.log)

[cmd_logs.zip](https://github.com/MrOlm/drep/files/4532813/cmd_logs.zip)

**Comment by MrOlm** [comment]
Hello,

This is a problem with pplacer, a module called by checkM, hitting the python recursion limit. This can happen when you have lots of genomes filling out the tree and are running checkM with "lineage_wf" (which is the default called by dRep)

To fix this, dRep has a flag "--set_recursion" in the "filter" module. So you have a couple of options for proceeding in this way: 1) Run the dRep modules one at a time, starting with "filter" with a high recursion limit, 2) Run dRep filter with a high recursion limit, parse the resulting "genomeInformation.csv" file, and then run dRep again using the same dereplicate command you did before but include a "--genomeInfo" file, or 3) use the flag  `--checkM_method taxonomy_wf`.

Best,
Matt

**Comment by sleepvet** [comment]
> Hello,
> 
> This is a problem with pplacer, a module called by checkM, hitting the python recursion limit. This can happen when you have lots of genomes filling out the tree and are running checkM with "lineage_wf" (which is the default called by dRep)
> 
> To fix this, dRep has a flag "--set_recursion" in the "filter" module. So you have a couple of options for proceeding in this way: 1) Run the dRep modules one at a time, starting with "filter" with a high recursion limit, 2) Run dRep filter with a high recursion limit, parse the resulting "genomeInformation.csv" file, and then run dRep again using the same dereplicate command you did before but include a "--genomeInfo" file, or 3) use the flag `--checkM_method taxonomy_wf`.
> 
> Best,
> Matt

It is working now, thank you very much!

**Comment by davised** [comment]
I had this issue as well. Trying with an increased recursion.

Is this information documented anywhere other than the help message? I was unable to find something immediately with a google search, so I assume other people are going to be a little confused as well.

Is this primarily due to including many genomes in the analysis at once? I'm looking at around 2500 currently. If there seems to be a specific genome count that causes issues, you could look for that number of inputs and print a warning message so that people know to check for this.

I thought my checkm wasn't configured properly, and spent some time re-running the checkm tests, confirming checkm db was up to date, etc. until I found the checkm recursion error and then the recursion error here. Since the hmm file seems to be missing each time, it would probably be worthwhile to throw a exists check in your code somewhere as well so that the error message is more informative.

Thanks for this amazing program. I think it's going to be standard issue going forward as the number of genome sequences seems to be increasing exponentially.

**Comment by MrOlm** [comment]
Urg, I wish it were as simple as just counting the number of genome inputs. It's really just that the program dendropy, a dependency of checkM, hits this limit in way that depends on the structure of the genome tree. So different sets of 2500 genomes will or will not hit this limit depending on their placement on the tree.

All the said I appreciate the feedback and will update the warning message to immediately suggest this in the future.

Best,
Matt

**Comment by davised** [comment]
Hi Matt,

Thanks for the quick response.

What a pity there isn't an easy fix. But I'm sure you would have
implemented it already if there was.

Anyway, I appreciate you putting my suggestions into action. I was poking
through the code to see how I could help but I have a feeling you'll get
faster results, especially if you're actively working on this project.

Cheers,

Ed

**Comment by MrOlm** [comment]
Hi Ed,

FYI, dRep now includes a link to this following page 

https://drep.readthedocs.io/en/latest/advanced_use.html#troubleshooting-checkm

when checkM fails.

Best,
Matt

**Comment by Caiyulu-818** [comment]
> https://drep.readthedocs.io/en/latest/advanced_use.html#troubleshooting-checkm

Hi,
I used the first method to set recursion to 3000 to clustering 4000 genomes, but it also errored. what can I do to solve this problem?
Best

**Comment by MrOlm** [comment]
Hi @Caiyulu-818 -

1) Make sure you're updated dRep and checkM to the latest versions

2) Run dRep with `-d` and check the output logs to make sure recursion is your problem, and not some other problem with checkM

3) You can always run checkM outside of dRep and just provide the results to dRep with `externalGenomeInfo`

Best,
Matt
