### ISSUE TITLE
Different numbers of primary clusters when running cluster module with different hierarchical linkage algorithms 

### ISSUE THREAD

**Issue by MeggyC** [MrOlm/drep#78]
Hey there, 

I've been running the cluster module using both single and average linkage modes on the same set of genomes, in order to compare the output. 

However, when I run the single mode dRep returns 887 primary clusters and 13550 animf comparisons. 
Conversely, when I run the average mode dRep returns 957 primary clusters and 7632 animf comparisons. 

I've tried both commands (signle and average) 3 times, and these numbers come back every time. 

I expected that this initial step, which uses MASH, did not employ hierarchical clustering, and that only secondary clustering did. 

Thanks in advance.

**Comment by MrOlm** [comment]
Hello,

Sorry for not mentioning this initially, but yes, the primary clustering (using Mash) is also done with hierarchical clustering. There is a figure made to show the clustering (called the primary clustering dendrogram), but because all genomes have to fit in the figure, sometimes it gets too big for matplotlib to actually make it.

The primary clustering is much less important than the secondary clustering, however, as it's only purpose is to reduce the computational load of the secondary clustering. The default value of 0.9 was set to ensure that genomes with >95% ANI end up in the same primary cluster, but you can also lower or raise this value well.

Let me know if you have any other questions.

Best,
Matt
