### ISSUE TITLE
How can I get competitors of winner genomes?

### ISSUE THREAD

**Issue by sleepvet** [MrOlm/drep#80]
I runed dRep dereplicate result/ -g *.fa -sa 0.99 --debug --checkM_method taxonomy_wf, and all 6000 genomes were dereplicated in to less than 5000. I can find all winner genomes, but cannot find thier competitors. I want to kown one specified winner genome and its failed competitors. What should I do?

**Comment by MrOlm** [comment]
Hello,

If you look in the resulting “data_tables” folder, you’ll see a file called Cdb.csv. This tells you the identity of each cluster of genomes (secondary_cluster). If you identify the secondary cluster of the genome of interest, all other genomes in the cluster are it’s “failed competitors”.

Best,
Matt

**Comment by sleepvet** [comment]
Thank you very much. But I'm still confused and need your help. I can only find winner's secondary_cluster in file Cdb.csv. The failed competitors are absent in this file. Where can I find other genomes in the cluster?

**Comment by MrOlm** [comment]
I see. All genomes that pass the genome filtering step make it into the Cdb.csv file, but genomes that get filtered out do not. I see from your note above that you used checkM for quality filtering - the genomes that you're looking for were probably excluded because they were too low quality. You can see the quality information for the genomes by looking at the file named `genomeInformation.csv`, and you can adjust the filtering chriteria with the following flags:

```FILTERING OPTIONS:
  -l LENGTH, --length LENGTH
                        Minimum genome length (default: 50000)
  -comp COMPLETENESS, --completeness COMPLETENESS
                        Minumum genome completeness (default: 75)
  -con CONTAMINATION, --contamination CONTAMINATION
                        Maximum genome contamination (default: 25)
  --ignoreGenomeQuality
                        Don't run checkM or do any quality filtering. NOT RECOMMENDED! This is useful for use with bacteriophages or eukaryotes or things where checkM scoring does
                        not work. Will only choose genomes based on length and N50 (default: False)```

Best,
Matt
