### ISSUE TITLE
Help could suggest using file instead of wildcard for -g (related #42)

### ISSUE THREAD

**Issue by alexdthomas** [MrOlm/drep#88]
Hi Matt, 

After years of using dRep I'd think I would know this, but I just spent > hour trying to figure out why it wouldn't run the way I always run it.  Turned out to be the same issue as #42 except I did not get an error that the argument list was too long, it just hung indefinitely until I had to use `kill <PID>` to end it.  I particularly noticed this after running dRep on 1904 genomes (which worked with wildcard) but it hung on 1934.  The example below hangs with 1900... 

Anyway, if the help (`-h`) could suggest using the file input for `-g` when dereplicating > n genomes that might help some folks out.  

Cheers, 
Alex 

Reproducible example (at least on our server, as pointed out OS specific...) 

```
while (( i++ < 5 )); do cp drep/tests/genomes/Enterococcus_casseliflavus_EC20.fasta "drep/tests/genomes/test_5_genomes/Enterococcus_casseliflavus_EC20_${i}.fasta"; done
dRep dereplicate out_dir -g /groups/banfield/users/talex/apps/drep/tests/genomes/test_5_genomes/*.fasta -p 16
#runs fine

while (( i++ < 1900 )); do cp drep/tests/genomes/Enterococcus_casseliflavus_EC20.fasta "drep/tests/genomes/test_1900_genomes/Enterococcus_casseliflavus_EC20_${i}.fasta"; done
dRep dereplicate out_dir -g /groups/banfield/users/talex/apps/drep/tests/genomes/test_1900_genomes/*.fasta -p 16
#hangs indefinitely
```

**Comment by MrOlm** [comment]
Hey Alex,

Thanks for the suggestion, but unfortunately I don't think is something that's possible to do. What's happening (I think) is that dRep is never actually being called- in the process of calling dRep, Unix is attempting to make a command that's too big and it fails. The expanding of wildcards happens before the program is called, so like, regardless of what you write it's going to fail and you're going to get the error message. Like I bet if you even run:

```ls  /groups/banfield/users/talex/apps/drep/tests/genomes/test_1900_genomes/*.fasta```

it'll hang with the same (lack of) error message. It's also dependent on the lengths of the path; going into the folder and running `*.fasta` instead of the full path with make a command string that's sorter (because it doesn't have to repeat the full path every time) and may not fail.

Should we open up a GitHub issue for Unix? 🙃

-Matt
